name: Sync to Hugging Face hub

on:
  push:
    branches: [master]  # or [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Ensure README metadata
        run: |
          if [ ! -f README.md ] || ! grep -q "^---" README.md; then
            cat <<EOF > README.md
---
title: Investment Thesis Bot
app_file: app.py
sdk: gradio
---
# Investment Thesis Bot
EOF
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add README.md
            git commit -m "Add/update README metadata"
          fi

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push --force https://het004:${HF_TOKEN}@huggingface.co/spaces/het004/Investment_Thesis_Bot master
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
