name: Sync to Hugging Face hub

on:
  push:
    branches: [master]  # or main if applicable
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Ensure README metadata
        run: |
          if [ ! -f README.md ] || ! grep -q "^---" README.md; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            cat > README.md <<'EOF'
---
title: Investment Thesis Bot
app_file: app.py
sdk: gradio
---

# Investment Thesis Bot

This app helps users analyze and generate investment theses.
EOF
            git add README.md
            git commit -m "Add/update README metadata"
          fi

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://het004:${HF_TOKEN}@huggingface.co/spaces/het004/Investment_Thesis_Bot master
